Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 37884 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 37057 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 56547 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 39730 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55782 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 38623 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 42942 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 46823 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 57639 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 39183 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36727 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60166 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 54959 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 59055 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 52003 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51201 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 36547 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 54037 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43747 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 54240 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 38733 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58917 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 49712 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 48987 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 34485 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 52024 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 59495 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 42666 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 56071 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 47157 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 53164 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 37930 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 39593 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 32811 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43568 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43257 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 41336 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 46776 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 56158 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43311 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 40198 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 58379 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 57424 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 57085 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 57089 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 51289 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 34583 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 49213 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55670 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55391 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45461 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 40769 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 43143 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 60569 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 40908 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 37949 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 45542 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55636 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 39220 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
/scr1/sumo/tools/traci/main.py:155: UserWarning: Could not connect to TraCI server using port 55915 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
Error: Sublane dynamics are not supported by mesoscopic simulation
Quitting (on error).
Traceback (most recent call last):
  File "/scr1/sumo/tests/../tests/complex/traci/bugs/ticket12810/runner.py", line 39, in <module>
    ] + sys.argv[1:])
  File "/scr1/sumo/tools/traci/main.py", line 147, in start
    result = init(sumoPort, numRetries, "localhost", label, sumoProcess, doSwitch, traceFile, traceGetters)
  File "/scr1/sumo/tools/traci/main.py", line 116, in init
    con = connect(port, numRetries, host, proc, 1, traceFile, traceGetters, label)
  File "/scr1/sumo/tools/traci/main.py", line 106, in connect
    raise FatalTraCIError("Could not connect in %s tries" % (numRetries + 1))
traci.exceptions.FatalTraCIError: Could not connect in 1 tries
